### ISSUE TITLE
Release JRuby 1.7 compatible version

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Cellect#39]
Hey @parrish I made a branch that will work with clients running JRuby. Can you cut a `0.0.10` release from https://github.com/zooniverse/Cellect/tree/jruby-1.7-compat, or give @camallen or I permissions to publish this gem on rubygems?

**Comment by parrish** [comment]
Yeah, I'm adding both of you anyway too.  Ed are you edward at cassetteta pe on rubygems?

**Comment by edpaget** [comment]
Thanks a bunch. I am indeed.

**Comment by parrish** [comment]
Cool.  Released to 0.1.2.pre.jruby : https://rubygems.org/gems/cellect/versions/0.1.2.pre.jruby

**Comment by edpaget** [comment]
:+1: thanks again
