### ISSUE TITLE
How does a user's diff_set get garbage collected?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Cellect#40]
I assume when the TTL for a user expires the `seen` ref [here](https://github.com/zooniverse/Cellect/blob/dd20ecacc1177902db0a7f836f167c315a846529/lib/cellect/server/user.rb#L16) is orhpaned and it's up the the GC to clean it up? 

Just doing some memory profiling and noticing ram doesn't decrease when the user's expire. Running MRI 2.2.0.

**Comment by parrish** [comment]
Pretty much, but it's a bit more explicit:
[User#ttl_expired!](https://github.com/zooniverse/Cellect/blob/dd20ecacc1177902db0a7f836f167c315a846529/lib/cellect/server/user.rb#L53) calls [Worfklow#remove_user](https://github.com/zooniverse/Cellect/blob/dd20ecacc1177902db0a7f836f167c315a846529/lib/cellect/server/workflow.rb#L62) which deletes the user from the hash.

The new incremental GC in Ruby is probably what you're seeing with the memory usage

**Comment by camallen** [comment]
Thanks.
