### ISSUE TITLE
specify a client timeout for HTTP connections

### ISSUE THREAD

**Issue by camallen** [zooniverse/Cellect#49]
The api may now use cellect in the request cycle and it'd be nice to timeout quickly. Can we provide some client configuration to drive the [HTTP call here](https://github.com/zooniverse/Cellect/blob/f04ac9c35045c96c527cc63a5b82fe7a2ea70ed0/lib/cellect/client/connection.rb#L62)?

**Comment by parrish** [comment]
We should just work on switching to the redis-backed branch, it's already [configurable here](https://github.com/zooniverse/Cellect/blob/attention/lib/cellect/client/connection.rb#L9) and [used here](https://github.com/zooniverse/Cellect/blob/attention/lib/cellect/client/connection.rb#L69)

**Comment by camallen** [comment]
magic!
