### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by astopy** [zooniverse/Cellect#52]
```
Installing listen 3.1.1

Gem::InstallError: listen requires Ruby version ~> 2.2.
Installing rspec 3.4.0
Installing virtus 1.0.5
Installing http-cookie 1.0.2
An error occurred while installing listen (3.1.1), and Bundler cannot continue.
Make sure that `gem install listen -v '3.1.1'` succeeds before bundling.
Removing intermediate container e18cace009cb
The command '/bin/sh -c bundle install' returned a non-zero code: 5
```

**Comment by parrish** [comment]
That's coming from guard which is specified as a development dependency, so I'm not sure why this is an issue.

> [Development dependencies](http://guides.rubygems.org/specification-reference/#add_development_dependency) aren't installed by default and aren't activated when a gem is required.

Failing that, we can just bump to 2.2.
